language: node_js

node_js:
  - '8'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn prettier:diff
  - yarn lint
# - yarn test

after_success:
  - yarn semantic-release -d
